In [12]:
cars = ["Ford", "Volvo", "BMW"]


In [13]:
x = cars[0]
print(x)
cars.pop(1)

Ford


'Volvo'

In [19]:

cars[0] = "Toyota"
x = len(cars)
print(x)

4


In [18]:
for x in cars:
  print(x)


Toyota
Volvo
BMW
Honda


In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [21]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [22]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [24]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])


[2 3 4 5]
[5 6]
